services:
  mysql:
    image: mysql/mysql-server:latest-aarch64
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=admin1
      - MYSQL_ROOT_HOST=%
    ports:
      - 3306:3306

  postgres:
    image: postgres:14.3-alpine
    restart: always
    environment:
      POSTGRES_USERNAME: root
      POSTGRES_PASSWORD: admin1
    ports:
      - 5432:5432

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
